## Canary CI/CD
name: Canary
run-name: Canary

on:
    push:
      branches:
        - *

#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'branch name'
#        required: false
#        default: 'master'
#      scripts-to-execute:
#        description: 'scripts to execute'
#        required: false
#        type: string
#        default: 'build lint type-check test'
#      is-patch-version:
#        description: "patch version"
#        required: true
#        type: boolean
#        default: false


jobs:
  set_stage_variable:
    runs-on: ubuntu-latest
    outputs:
      id: stage
      value: ${{ steps.stage.outputs.stage }}
    steps:
      - name: Output stage
        id: stage
        run: |
          if [[ "${{ inputs.is-patch-version }}" == "true" ]]; then
            stage="patch"
          else
            stage="canary"
          fi
          echo $stage
          echo "stage=${stage}" >> $GITHUB_OUTPUT
  get_branch_name:
    runs-on: ubuntu-latest
    outputs:
      id: branch-name
      value: ${{ steps.branch-name.outputs.name }}
    steps:
      - name: Output branch name
        id: name
        run: |
          name=$(echo ${GITHUB_REF#refs/heads/})
          echo $name
          echo "name=${name}" >> $GITHUB_OUTPUT
#  canary:
#    uses: kaltura/playkit-js-common/.github/workflows/canary_player.yaml@master
#    secrets: inherit
#    with:
#      node-version: "20.x"
#      player-type: "ovp tv"
#      schema-type: "playerV3Versions"
#      tests-yarn-run-to-execute: ${{ inputs.scripts-to-execute }}
#      yarn-upgrade-list: ""
#      is-patch-version: ${{ inputs.is-patch-version }}
#      stage: $STAGE_VALUE
#      stage: ${{ needs.set_stage_variable.outputs.stage }}
