

## Patch
name: Patch
run-name: Patch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name'
        required: false
        default: 'patch-version'

jobs:
  prod:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_cicd.yaml@master
    secrets:
      PLAYER_CENTRAL_ACCOUNT_ID: ${{ secrets.PLAYER_CENTRAL_ACCOUNT_ID }}
      PLAYER_SERVICES_ACCOUNT_ID: ${{ secrets.PLAYER_SERVICES_ACCOUNT_ID }}
      PLAYER_S3_BUCKET_DEPLOYMENT: ${{ secrets.PLAYER_S3_BUCKET_DEPLOYMENT }}
      PLAYER_S3_BUCKET_APPS: ${{ secrets.PLAYER_S3_BUCKET_APPS }}
      PLAYER_NPM_TOKEN: ${{ secrets.PLAYER_NPM_TOKEN }}
      PLAYER_LAMBDA_NAME: ${{ secrets.PLAYER_LAMBDA_NAME }}
      PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
      PLAYER_GITHUB_BOT_TOKEN: ${{ secrets.PLAYER_GITHUB_BOT_TOKEN }}
    with:
      node-version: "20.x"
      type: "player"
      env: "patch"
      player-type: "ovp tv"
      schema-type: "playerV3Versions"
      tests-yarn-run-to-execute: 'build lint type-check test'

